### ISSUE TITLE
additionalProperties is not supported

### ISSUE THREAD

**Issue by agandrabur** [pace/bricks#105] opened 2019-09-09 08:39 UTC
OpenAPIv3 specs additionalProperties is not supported

```yaml
type: object
additionalProperties: true
```
This should generate a `map[string]interface{}`

```yaml
components:
  schemas:
    Messages:        # <---- dictionary
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        code:
          type: integer
        text:
          type: string
```
This should generate a `map[string]Message`

**Comment by threez** [comment] 2019-09-09 09:13
@agandrabur thanks for the report, that is a duplicate of https://github.com/pace/bricks/issues/61, can you address all issued of it?

Duplicate of #61

**Closed by threez** 2019-09-09 09:13 UTC
